#library("lme4")
library("lmerTest")
t <- read.csv("results.csv")
Personf <- factor(t$Person)
LogRt <- log(t$Rt)
#fit <- lmer(t$Rt ~ t$Hit + (1|Personf))
fit <- lmer(LogRt ~ t$Hit + (1|Personf))
print("-----------------------------------------")
print(summary(fit))
print("-----------------------------------------")
print(anova(fit))
print("-----------------------------------------")
#print(anova(fit), type=1)
st <- step(fit)
#plot(st)
#plot(1:10)
plot(fit)
